// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: control_plane.proto

package control_plane

import (
	southbound "github.com/Laboratory-for-Safe-and-Secure-Systems/kritis3m_proto/southbound"
	empty "github.com/golang/protobuf/ptypes/empty"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateState int32

const (
	UpdateState_UPDATE_ERROR        UpdateState = 0
	UpdateState_UPDATE_ROLLBACK     UpdateState = 1
	UpdateState_UPDATE_APPLICABLE   UpdateState = 2
	UpdateState_UPDATE_APPLY_REQ    UpdateState = 3
	UpdateState_UPDATE_APPLIED      UpdateState = 4
	UpdateState_UPDATE_ACKNOWLEDGED UpdateState = 5
	UpdateState_UPDATE_PUBLISHED    UpdateState = 6
)

// Enum value maps for UpdateState.
var (
	UpdateState_name = map[int32]string{
		0: "UPDATE_ERROR",
		1: "UPDATE_ROLLBACK",
		2: "UPDATE_APPLICABLE",
		3: "UPDATE_APPLY_REQ",
		4: "UPDATE_APPLIED",
		5: "UPDATE_ACKNOWLEDGED",
		6: "UPDATE_PUBLISHED",
	}
	UpdateState_value = map[string]int32{
		"UPDATE_ERROR":        0,
		"UPDATE_ROLLBACK":     1,
		"UPDATE_APPLICABLE":   2,
		"UPDATE_APPLY_REQ":    3,
		"UPDATE_APPLIED":      4,
		"UPDATE_ACKNOWLEDGED": 5,
		"UPDATE_PUBLISHED":    6,
	}
)

func (x UpdateState) Enum() *UpdateState {
	p := new(UpdateState)
	*p = x
	return p
}

func (x UpdateState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateState) Descriptor() protoreflect.EnumDescriptor {
	return file_control_plane_proto_enumTypes[0].Descriptor()
}

func (UpdateState) Type() protoreflect.EnumType {
	return &file_control_plane_proto_enumTypes[0]
}

func (x UpdateState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateState.Descriptor instead.
func (UpdateState) EnumDescriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{0}
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          int32                  `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTxId() int32 {
	if x != nil {
		return x.TxId
	}
	return 0
}

type NodeUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeUpdateItem *NodeUpdateItem        `protobuf:"bytes,1,opt,name=node_update_item,json=nodeUpdateItem,proto3" json:"node_update_item,omitempty"`
	Transaction    *Transaction           `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeUpdate) Reset() {
	*x = NodeUpdate{}
	mi := &file_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUpdate) ProtoMessage() {}

func (x *NodeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUpdate.ProtoReflect.Descriptor instead.
func (*NodeUpdate) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *NodeUpdate) GetNodeUpdateItem() *NodeUpdateItem {
	if x != nil {
		return x.NodeUpdateItem
	}
	return nil
}

func (x *NodeUpdate) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type NodeUpdateItem struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	SerialNumber     string                       `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	NetworkIndex     int32                        `protobuf:"varint,3,opt,name=network_index,json=networkIndex,proto3" json:"network_index,omitempty"`
	Locality         string                       `protobuf:"bytes,4,opt,name=locality,proto3" json:"locality,omitempty"`
	VersionSetId     string                       `protobuf:"bytes,5,opt,name=version_set_id,json=versionSetId,proto3" json:"version_set_id,omitempty"`
	HardwareConfig   []*southbound.HardwareConfig `protobuf:"bytes,6,rep,name=hardware_config,json=hardwareConfig,proto3" json:"hardware_config,omitempty"`
	GroupProxyUpdate []*GroupProxyUpdate          `protobuf:"bytes,7,rep,name=group_proxy_update,json=groupProxyUpdate,proto3" json:"group_proxy_update,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeUpdateItem) Reset() {
	*x = NodeUpdateItem{}
	mi := &file_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUpdateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUpdateItem) ProtoMessage() {}

func (x *NodeUpdateItem) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUpdateItem.ProtoReflect.Descriptor instead.
func (*NodeUpdateItem) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *NodeUpdateItem) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *NodeUpdateItem) GetNetworkIndex() int32 {
	if x != nil {
		return x.NetworkIndex
	}
	return 0
}

func (x *NodeUpdateItem) GetLocality() string {
	if x != nil {
		return x.Locality
	}
	return ""
}

func (x *NodeUpdateItem) GetVersionSetId() string {
	if x != nil {
		return x.VersionSetId
	}
	return ""
}

func (x *NodeUpdateItem) GetHardwareConfig() []*southbound.HardwareConfig {
	if x != nil {
		return x.HardwareConfig
	}
	return nil
}

func (x *NodeUpdateItem) GetGroupProxyUpdate() []*GroupProxyUpdate {
	if x != nil {
		return x.GroupProxyUpdate
	}
	return nil
}

type UpdateProxy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ServerEndpointAddr string                 `protobuf:"bytes,2,opt,name=server_endpoint_addr,json=serverEndpointAddr,proto3" json:"server_endpoint_addr,omitempty"`
	ClientEndpointAddr string                 `protobuf:"bytes,3,opt,name=client_endpoint_addr,json=clientEndpointAddr,proto3" json:"client_endpoint_addr,omitempty"`
	ProxyType          southbound.ProxyType   `protobuf:"varint,4,opt,name=proxy_type,json=proxyType,proto3,enum=node.ProxyType" json:"proxy_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateProxy) Reset() {
	*x = UpdateProxy{}
	mi := &file_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProxy) ProtoMessage() {}

func (x *UpdateProxy) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProxy.ProtoReflect.Descriptor instead.
func (*UpdateProxy) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProxy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProxy) GetServerEndpointAddr() string {
	if x != nil {
		return x.ServerEndpointAddr
	}
	return ""
}

func (x *UpdateProxy) GetClientEndpointAddr() string {
	if x != nil {
		return x.ClientEndpointAddr
	}
	return ""
}

func (x *UpdateProxy) GetProxyType() southbound.ProxyType {
	if x != nil {
		return x.ProxyType
	}
	return southbound.ProxyType(0)
}

type GroupProxyUpdate struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	GroupName      string                     `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	EndpointConfig *southbound.EndpointConfig `protobuf:"bytes,2,opt,name=endpoint_config,json=endpointConfig,proto3" json:"endpoint_config,omitempty"`
	LegacyConfig   *southbound.EndpointConfig `protobuf:"bytes,3,opt,name=legacy_config,json=legacyConfig,proto3,oneof" json:"legacy_config,omitempty"`
	GroupLogLevel  int32                      `protobuf:"varint,4,opt,name=group_log_level,json=groupLogLevel,proto3" json:"group_log_level,omitempty"`
	Proxies        []*UpdateProxy             `protobuf:"bytes,5,rep,name=proxies,proto3" json:"proxies,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupProxyUpdate) Reset() {
	*x = GroupProxyUpdate{}
	mi := &file_control_plane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupProxyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupProxyUpdate) ProtoMessage() {}

func (x *GroupProxyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupProxyUpdate.ProtoReflect.Descriptor instead.
func (*GroupProxyUpdate) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{4}
}

func (x *GroupProxyUpdate) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupProxyUpdate) GetEndpointConfig() *southbound.EndpointConfig {
	if x != nil {
		return x.EndpointConfig
	}
	return nil
}

func (x *GroupProxyUpdate) GetLegacyConfig() *southbound.EndpointConfig {
	if x != nil {
		return x.LegacyConfig
	}
	return nil
}

func (x *GroupProxyUpdate) GetGroupLogLevel() int32 {
	if x != nil {
		return x.GroupLogLevel
	}
	return 0
}

func (x *GroupProxyUpdate) GetProxies() []*UpdateProxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

type FleetUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Transaction     *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	NodeUpdateItems []*NodeUpdateItem      `protobuf:"bytes,2,rep,name=node_update_items,json=nodeUpdateItems,proto3" json:"node_update_items,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FleetUpdate) Reset() {
	*x = FleetUpdate{}
	mi := &file_control_plane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetUpdate) ProtoMessage() {}

func (x *FleetUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetUpdate.ProtoReflect.Descriptor instead.
func (*FleetUpdate) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{5}
}

func (x *FleetUpdate) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *FleetUpdate) GetNodeUpdateItems() []*NodeUpdateItem {
	if x != nil {
		return x.NodeUpdateItems
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateState   UpdateState            `protobuf:"varint,1,opt,name=update_state,json=updateState,proto3,enum=control_service.UpdateState" json:"update_state,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Meta          *_struct.Struct        `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	TxId          int32                  `protobuf:"varint,4,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_control_plane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetUpdateState() UpdateState {
	if x != nil {
		return x.UpdateState
	}
	return UpdateState_UPDATE_ERROR
}

func (x *UpdateResponse) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *UpdateResponse) GetMeta() *_struct.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *UpdateResponse) GetTxId() int32 {
	if x != nil {
		return x.TxId
	}
	return 0
}

func (x *UpdateResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type FleetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateState   UpdateState            `protobuf:"varint,1,opt,name=update_state,json=updateState,proto3,enum=control_service.UpdateState" json:"update_state,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Meta          string                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	TxId          int32                  `protobuf:"varint,4,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetResponse) Reset() {
	*x = FleetResponse{}
	mi := &file_control_plane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetResponse) ProtoMessage() {}

func (x *FleetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetResponse.ProtoReflect.Descriptor instead.
func (*FleetResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{7}
}

func (x *FleetResponse) GetUpdateState() UpdateState {
	if x != nil {
		return x.UpdateState
	}
	return UpdateState_UPDATE_ERROR
}

func (x *FleetResponse) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FleetResponse) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *FleetResponse) GetTxId() int32 {
	if x != nil {
		return x.TxId
	}
	return 0
}

type CertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	CertType      southbound.CertType    `protobuf:"varint,2,opt,name=cert_type,json=certType,proto3,enum=node.CertType" json:"cert_type,omitempty"`
	HostName      string                 `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	IpAddr        string                 `protobuf:"bytes,4,opt,name=ip_addr,json=ipAddr,proto3" json:"ip_addr,omitempty"`
	Port          uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Algo          *string                `protobuf:"bytes,6,opt,name=algo,proto3,oneof" json:"algo,omitempty"`
	AltAlgo       *string                `protobuf:"bytes,7,opt,name=alt_algo,json=altAlgo,proto3,oneof" json:"alt_algo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	mi := &file_control_plane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{8}
}

func (x *CertificateRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *CertificateRequest) GetCertType() southbound.CertType {
	if x != nil {
		return x.CertType
	}
	return southbound.CertType(0)
}

func (x *CertificateRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *CertificateRequest) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *CertificateRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CertificateRequest) GetAlgo() string {
	if x != nil && x.Algo != nil {
		return *x.Algo
	}
	return ""
}

func (x *CertificateRequest) GetAltAlgo() string {
	if x != nil && x.AltAlgo != nil {
		return *x.AltAlgo
	}
	return ""
}

type CertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Retcode       int32                  `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateResponse) Reset() {
	*x = CertificateResponse{}
	mi := &file_control_plane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateResponse) ProtoMessage() {}

func (x *CertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateResponse.ProtoReflect.Descriptor instead.
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{9}
}

func (x *CertificateResponse) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_control_plane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{10}
}

func (x *HelloResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Level         *int32                 `protobuf:"varint,3,opt,name=level,proto3,oneof" json:"level,omitempty"`
	Module        *string                `protobuf:"bytes,4,opt,name=module,proto3,oneof" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_control_plane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{11}
}

func (x *LogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *LogResponse) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *LogResponse) GetModule() string {
	if x != nil && x.Module != nil {
		return *x.Module
	}
	return ""
}

var File_control_plane_proto protoreflect.FileDescriptor

const file_control_plane_proto_rawDesc = "" +
	"\n" +
	"\x13control_plane.proto\x12\x0fcontrol_service\x1a\n" +
	"node.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\"\n" +
	"\vTransaction\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\x05R\x04txId\"\x97\x01\n" +
	"\n" +
	"NodeUpdate\x12I\n" +
	"\x10node_update_item\x18\x01 \x01(\v2\x1f.control_service.NodeUpdateItemR\x0enodeUpdateItem\x12>\n" +
	"\vtransaction\x18\x02 \x01(\v2\x1c.control_service.TransactionR\vtransaction\"\xac\x02\n" +
	"\x0eNodeUpdateItem\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12#\n" +
	"\rnetwork_index\x18\x03 \x01(\x05R\fnetworkIndex\x12\x1a\n" +
	"\blocality\x18\x04 \x01(\tR\blocality\x12$\n" +
	"\x0eversion_set_id\x18\x05 \x01(\tR\fversionSetId\x12=\n" +
	"\x0fhardware_config\x18\x06 \x03(\v2\x14.node.HardwareConfigR\x0ehardwareConfig\x12O\n" +
	"\x12group_proxy_update\x18\a \x03(\v2!.control_service.GroupProxyUpdateR\x10groupProxyUpdate\"\xb5\x01\n" +
	"\vUpdateProxy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x14server_endpoint_addr\x18\x02 \x01(\tR\x12serverEndpointAddr\x120\n" +
	"\x14client_endpoint_addr\x18\x03 \x01(\tR\x12clientEndpointAddr\x12.\n" +
	"\n" +
	"proxy_type\x18\x04 \x01(\x0e2\x0f.node.ProxyTypeR\tproxyType\"\xa2\x02\n" +
	"\x10GroupProxyUpdate\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12=\n" +
	"\x0fendpoint_config\x18\x02 \x01(\v2\x14.node.EndpointConfigR\x0eendpointConfig\x12>\n" +
	"\rlegacy_config\x18\x03 \x01(\v2\x14.node.EndpointConfigH\x00R\flegacyConfig\x88\x01\x01\x12&\n" +
	"\x0fgroup_log_level\x18\x04 \x01(\x05R\rgroupLogLevel\x126\n" +
	"\aproxies\x18\x05 \x03(\v2\x1c.control_service.UpdateProxyR\aproxiesB\x10\n" +
	"\x0e_legacy_config\"\x9a\x01\n" +
	"\vFleetUpdate\x12>\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1c.control_service.TransactionR\vtransaction\x12K\n" +
	"\x11node_update_items\x18\x02 \x03(\v2\x1f.control_service.NodeUpdateItemR\x0fnodeUpdateItems\"\xe6\x01\n" +
	"\x0eUpdateResponse\x12?\n" +
	"\fupdate_state\x18\x01 \x01(\x0e2\x1c.control_service.UpdateStateR\vupdateState\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x04meta\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04meta\x12\x13\n" +
	"\x05tx_id\x18\x04 \x01(\x05R\x04txId\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\"\xb3\x01\n" +
	"\rFleetResponse\x12?\n" +
	"\fupdate_state\x18\x01 \x01(\x0e2\x1c.control_service.UpdateStateR\vupdateState\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\x12\x13\n" +
	"\x05tx_id\x18\x04 \x01(\x05R\x04txId\"\xff\x01\n" +
	"\x12CertificateRequest\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12+\n" +
	"\tcert_type\x18\x02 \x01(\x0e2\x0e.node.CertTypeR\bcertType\x12\x1b\n" +
	"\thost_name\x18\x03 \x01(\tR\bhostName\x12\x17\n" +
	"\aip_addr\x18\x04 \x01(\tR\x06ipAddr\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12\x17\n" +
	"\x04algo\x18\x06 \x01(\tH\x00R\x04algo\x88\x01\x01\x12\x1e\n" +
	"\balt_algo\x18\a \x01(\tH\x01R\aaltAlgo\x88\x01\x01B\a\n" +
	"\x05_algoB\v\n" +
	"\t_alt_algo\"/\n" +
	"\x13CertificateResponse\x12\x18\n" +
	"\aretcode\x18\x01 \x01(\x05R\aretcode\"4\n" +
	"\rHelloResponse\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\"\x99\x01\n" +
	"\vLogResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x19\n" +
	"\x05level\x18\x03 \x01(\x05H\x00R\x05level\x88\x01\x01\x12\x1b\n" +
	"\x06module\x18\x04 \x01(\tH\x01R\x06module\x88\x01\x01B\b\n" +
	"\x06_levelB\t\n" +
	"\a_module*\xa4\x01\n" +
	"\vUpdateState\x12\x10\n" +
	"\fUPDATE_ERROR\x10\x00\x12\x13\n" +
	"\x0fUPDATE_ROLLBACK\x10\x01\x12\x15\n" +
	"\x11UPDATE_APPLICABLE\x10\x02\x12\x14\n" +
	"\x10UPDATE_APPLY_REQ\x10\x03\x12\x12\n" +
	"\x0eUPDATE_APPLIED\x10\x04\x12\x17\n" +
	"\x13UPDATE_ACKNOWLEDGED\x10\x05\x12\x14\n" +
	"\x10UPDATE_PUBLISHED\x10\x062\x92\x03\n" +
	"\fControlPlane\x12L\n" +
	"\n" +
	"UpdateNode\x12\x1b.control_service.NodeUpdate\x1a\x1f.control_service.UpdateResponse0\x01\x12M\n" +
	"\vUpdateFleet\x12\x1c.control_service.FleetUpdate\x1a\x1e.control_service.FleetResponse0\x01\x12c\n" +
	"\x16SendCertificateRequest\x12#.control_service.CertificateRequest\x1a$.control_service.CertificateResponse\x12A\n" +
	"\x05hello\x12\x16.google.protobuf.Empty\x1a\x1e.control_service.HelloResponse0\x01\x12=\n" +
	"\x03log\x12\x16.google.protobuf.Empty\x1a\x1c.control_service.LogResponse0\x01BPZNgithub.com/Laboratory-for-Safe-and-Secure-Systems/kritis3m_proto/control_planeb\x06proto3"

var (
	file_control_plane_proto_rawDescOnce sync.Once
	file_control_plane_proto_rawDescData []byte
)

func file_control_plane_proto_rawDescGZIP() []byte {
	file_control_plane_proto_rawDescOnce.Do(func() {
		file_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_plane_proto_rawDesc), len(file_control_plane_proto_rawDesc)))
	})
	return file_control_plane_proto_rawDescData
}

var file_control_plane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_control_plane_proto_goTypes = []any{
	(UpdateState)(0),                  // 0: control_service.UpdateState
	(*Transaction)(nil),               // 1: control_service.Transaction
	(*NodeUpdate)(nil),                // 2: control_service.NodeUpdate
	(*NodeUpdateItem)(nil),            // 3: control_service.NodeUpdateItem
	(*UpdateProxy)(nil),               // 4: control_service.UpdateProxy
	(*GroupProxyUpdate)(nil),          // 5: control_service.GroupProxyUpdate
	(*FleetUpdate)(nil),               // 6: control_service.FleetUpdate
	(*UpdateResponse)(nil),            // 7: control_service.UpdateResponse
	(*FleetResponse)(nil),             // 8: control_service.FleetResponse
	(*CertificateRequest)(nil),        // 9: control_service.CertificateRequest
	(*CertificateResponse)(nil),       // 10: control_service.CertificateResponse
	(*HelloResponse)(nil),             // 11: control_service.HelloResponse
	(*LogResponse)(nil),               // 12: control_service.LogResponse
	(*southbound.HardwareConfig)(nil), // 13: node.HardwareConfig
	(southbound.ProxyType)(0),         // 14: node.ProxyType
	(*southbound.EndpointConfig)(nil), // 15: node.EndpointConfig
	(*timestamp.Timestamp)(nil),       // 16: google.protobuf.Timestamp
	(*_struct.Struct)(nil),            // 17: google.protobuf.Struct
	(southbound.CertType)(0),          // 18: node.CertType
	(*empty.Empty)(nil),               // 19: google.protobuf.Empty
}
var file_control_plane_proto_depIdxs = []int32{
	3,  // 0: control_service.NodeUpdate.node_update_item:type_name -> control_service.NodeUpdateItem
	1,  // 1: control_service.NodeUpdate.transaction:type_name -> control_service.Transaction
	13, // 2: control_service.NodeUpdateItem.hardware_config:type_name -> node.HardwareConfig
	5,  // 3: control_service.NodeUpdateItem.group_proxy_update:type_name -> control_service.GroupProxyUpdate
	14, // 4: control_service.UpdateProxy.proxy_type:type_name -> node.ProxyType
	15, // 5: control_service.GroupProxyUpdate.endpoint_config:type_name -> node.EndpointConfig
	15, // 6: control_service.GroupProxyUpdate.legacy_config:type_name -> node.EndpointConfig
	4,  // 7: control_service.GroupProxyUpdate.proxies:type_name -> control_service.UpdateProxy
	1,  // 8: control_service.FleetUpdate.transaction:type_name -> control_service.Transaction
	3,  // 9: control_service.FleetUpdate.node_update_items:type_name -> control_service.NodeUpdateItem
	0,  // 10: control_service.UpdateResponse.update_state:type_name -> control_service.UpdateState
	16, // 11: control_service.UpdateResponse.timestamp:type_name -> google.protobuf.Timestamp
	17, // 12: control_service.UpdateResponse.meta:type_name -> google.protobuf.Struct
	0,  // 13: control_service.FleetResponse.update_state:type_name -> control_service.UpdateState
	16, // 14: control_service.FleetResponse.timestamp:type_name -> google.protobuf.Timestamp
	18, // 15: control_service.CertificateRequest.cert_type:type_name -> node.CertType
	2,  // 16: control_service.ControlPlane.UpdateNode:input_type -> control_service.NodeUpdate
	6,  // 17: control_service.ControlPlane.UpdateFleet:input_type -> control_service.FleetUpdate
	9,  // 18: control_service.ControlPlane.SendCertificateRequest:input_type -> control_service.CertificateRequest
	19, // 19: control_service.ControlPlane.hello:input_type -> google.protobuf.Empty
	19, // 20: control_service.ControlPlane.log:input_type -> google.protobuf.Empty
	7,  // 21: control_service.ControlPlane.UpdateNode:output_type -> control_service.UpdateResponse
	8,  // 22: control_service.ControlPlane.UpdateFleet:output_type -> control_service.FleetResponse
	10, // 23: control_service.ControlPlane.SendCertificateRequest:output_type -> control_service.CertificateResponse
	11, // 24: control_service.ControlPlane.hello:output_type -> control_service.HelloResponse
	12, // 25: control_service.ControlPlane.log:output_type -> control_service.LogResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_control_plane_proto_init() }
func file_control_plane_proto_init() {
	if File_control_plane_proto != nil {
		return
	}
	file_control_plane_proto_msgTypes[4].OneofWrappers = []any{}
	file_control_plane_proto_msgTypes[8].OneofWrappers = []any{}
	file_control_plane_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_plane_proto_rawDesc), len(file_control_plane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_plane_proto_goTypes,
		DependencyIndexes: file_control_plane_proto_depIdxs,
		EnumInfos:         file_control_plane_proto_enumTypes,
		MessageInfos:      file_control_plane_proto_msgTypes,
	}.Build()
	File_control_plane_proto = out.File
	file_control_plane_proto_goTypes = nil
	file_control_plane_proto_depIdxs = nil
}
