// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: est.proto

package est

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollCallRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EstSerialNumber    string                 `protobuf:"bytes,1,opt,name=est_serial_number,json=estSerialNumber,proto3" json:"est_serial_number,omitempty"`
	SerialNumber       string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Organization       string                 `protobuf:"bytes,3,opt,name=organization,proto3" json:"organization,omitempty"`
	IssuedAt           *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt          *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SignatureAlgorithm string                 `protobuf:"bytes,6,opt,name=signature_algorithm,json=signatureAlgorithm,proto3" json:"signature_algorithm,omitempty"`
	Plane              string                 `protobuf:"bytes,7,opt,name=plane,proto3" json:"plane,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnrollCallRequest) Reset() {
	*x = EnrollCallRequest{}
	mi := &file_est_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollCallRequest) ProtoMessage() {}

func (x *EnrollCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_est_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollCallRequest.ProtoReflect.Descriptor instead.
func (*EnrollCallRequest) Descriptor() ([]byte, []int) {
	return file_est_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollCallRequest) GetEstSerialNumber() string {
	if x != nil {
		return x.EstSerialNumber
	}
	return ""
}

func (x *EnrollCallRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *EnrollCallRequest) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *EnrollCallRequest) GetIssuedAt() *timestamp.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *EnrollCallRequest) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *EnrollCallRequest) GetSignatureAlgorithm() string {
	if x != nil {
		return x.SignatureAlgorithm
	}
	return ""
}

func (x *EnrollCallRequest) GetPlane() string {
	if x != nil {
		return x.Plane
	}
	return ""
}

type EnrollCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Retval        int32                  `protobuf:"varint,1,opt,name=retval,proto3" json:"retval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollCallResponse) Reset() {
	*x = EnrollCallResponse{}
	mi := &file_est_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollCallResponse) ProtoMessage() {}

func (x *EnrollCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_est_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollCallResponse.ProtoReflect.Descriptor instead.
func (*EnrollCallResponse) Descriptor() ([]byte, []int) {
	return file_est_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollCallResponse) GetRetval() int32 {
	if x != nil {
		return x.Retval
	}
	return 0
}

var File_est_proto protoreflect.FileDescriptor

const file_est_proto_rawDesc = "" +
	"\n" +
	"\test.proto\x12\x03est\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x02\n" +
	"\x11EnrollCallRequest\x12*\n" +
	"\x11est_serial_number\x18\x01 \x01(\tR\x0festSerialNumber\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\"\n" +
	"\forganization\x18\x03 \x01(\tR\forganization\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12/\n" +
	"\x13signature_algorithm\x18\x06 \x01(\tR\x12signatureAlgorithm\x12\x14\n" +
	"\x05plane\x18\a \x01(\tR\x05plane\",\n" +
	"\x12EnrollCallResponse\x12\x16\n" +
	"\x06retval\x18\x01 \x01(\x05R\x06retval2K\n" +
	"\n" +
	"EstService\x12=\n" +
	"\n" +
	"EnrollCall\x12\x16.est.EnrollCallRequest\x1a\x17.est.EnrollCallResponseBFZDgithub.com/Laboratory-for-Safe-and-Secure-Systems/kritis3m_proto/estb\x06proto3"

var (
	file_est_proto_rawDescOnce sync.Once
	file_est_proto_rawDescData []byte
)

func file_est_proto_rawDescGZIP() []byte {
	file_est_proto_rawDescOnce.Do(func() {
		file_est_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_est_proto_rawDesc), len(file_est_proto_rawDesc)))
	})
	return file_est_proto_rawDescData
}

var file_est_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_est_proto_goTypes = []any{
	(*EnrollCallRequest)(nil),   // 0: est.EnrollCallRequest
	(*EnrollCallResponse)(nil),  // 1: est.EnrollCallResponse
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_est_proto_depIdxs = []int32{
	2, // 0: est.EnrollCallRequest.issued_at:type_name -> google.protobuf.Timestamp
	2, // 1: est.EnrollCallRequest.expires_at:type_name -> google.protobuf.Timestamp
	0, // 2: est.EstService.EnrollCall:input_type -> est.EnrollCallRequest
	1, // 3: est.EstService.EnrollCall:output_type -> est.EnrollCallResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_est_proto_init() }
func file_est_proto_init() {
	if File_est_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_est_proto_rawDesc), len(file_est_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_est_proto_goTypes,
		DependencyIndexes: file_est_proto_depIdxs,
		MessageInfos:      file_est_proto_msgTypes,
	}.Build()
	File_est_proto = out.File
	file_est_proto_goTypes = nil
	file_est_proto_depIdxs = nil
}
